---
abstract: unknown
author:
  - 'Andreas Lund <floyd@atc.no>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.131560'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: cet.pl
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5
version: 2.00
